# Generated by Django 4.2.8 on 2026-09-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='recommendation_1',
            field=models.CharField(default='Not Recommended Yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='recommendation_2',
            field=models.CharField(default='Not Recommended Yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='recommendation_3',
            field=models.CharField(default='Not Recommended Yet', max_length=100),
        ),
    ]
