# Generated by Django 5.2.17 on 2026-09-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_careerroadmapstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerRoadmapStudent',
        ),
    ]
