# Generated by Django 5.2.17 on 2026-09-06 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_careerroadmapstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRoadmapStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list_of_careers', models.ManyToManyField(related_name='recommended_to_students', to='api.careerroadmap')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roadmap_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
