# Generated by Django 5.2.17 on 2026-09-06 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_careerroadmapstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerroadmapstudent',
            name='list_of_careers',
        ),
        migrations.AddField(
            model_name='careerroadmapstudent',
            name='list_of_careers',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to_students', to='api.careerroadmap'),
        ),
    ]
