# Generated by Django 5.2.17 on 2026-09-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_careerroadmapstudent_list_of_careers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerRoadmapStudent',
        ),
    ]
